// Code generated by goctl. DO NOT EDIT.
// Source: UserMessage.proto

package usermessage

import (
	"context"
	userMessagePb2 "douyin/pkg/message/userMessagePb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Message        = userMessagePb2.Message
	MessageListReq = userMessagePb2.MessageListReq
	MessageListRes = userMessagePb2.MessageListRes
	MessageReq     = userMessagePb2.MessageReq
	MessageRes     = userMessagePb2.MessageRes

	UserMessage interface {
		// -----------------------SendMessage-----------------------
		SendMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageRes, error)
		// -----------------------GetMessageList-----------------------
		GetMessageList(ctx context.Context, in *MessageListReq, opts ...grpc.CallOption) (*MessageListRes, error)
	}

	defaultUserMessage struct {
		cli zrpc.Client
	}
)

func NewUserMessage(cli zrpc.Client) UserMessage {
	return &defaultUserMessage{
		cli: cli,
	}
}

// -----------------------SendMessage-----------------------
func (m *defaultUserMessage) SendMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*MessageRes, error) {
	client := userMessagePb2.NewUserMessageClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

// -----------------------GetMessageList-----------------------
func (m *defaultUserMessage) GetMessageList(ctx context.Context, in *MessageListReq, opts ...grpc.CallOption) (*MessageListRes, error) {
	client := userMessagePb2.NewUserMessageClient(m.cli.Conn())
	return client.GetMessageList(ctx, in, opts...)
}
