// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package commentservice

import (
	"context"

	"comment/rpc/types/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                     = comment.Comment
	DouyinCommentActionRequest  = comment.DouyinCommentActionRequest
	DouyinCommentActionResponse = comment.DouyinCommentActionResponse
	DouyinCommentListRequest    = comment.DouyinCommentListRequest
	DouyinCommentListResponse   = comment.DouyinCommentListResponse
	User                        = comment.User

	CommentService interface {
		CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error)
		CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error)
	}

	defaultCommentService struct {
		cli zrpc.Client
	}
)

func NewCommentService(cli zrpc.Client) CommentService {
	return &defaultCommentService{
		cli: cli,
	}
}

func (m *defaultCommentService) CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.CommentAction(ctx, in, opts...)
}

func (m *defaultCommentService) CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error) {
	client := comment.NewCommentServiceClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}
