// Code generated by goctl. DO NOT EDIT.
// Source: UserOptService.proto

package server

import (
	"context"
	logic2 "douyin/pkg/favorite/internal/logic"
	"douyin/pkg/favorite/internal/svc"
	userOptPb2 "douyin/pkg/favorite/userOptPb"
)

type UserOptServiceServer struct {
	svcCtx *svc.ServiceContext
	userOptPb2.UnimplementedUserOptServiceServer
}

func NewUserOptServiceServer(svcCtx *svc.ServiceContext) *UserOptServiceServer {
	return &UserOptServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------userFavoriteList-----------------------
func (s *UserOptServiceServer) GetUserFavorite(ctx context.Context, in *userOptPb2.GetUserFavoriteReq) (*userOptPb2.GetUserFavoriteResp, error) {
	l := logic2.NewGetUserFavoriteLogic(ctx, s.svcCtx)
	return l.GetUserFavorite(in)
}

func (s *UserOptServiceServer) UpdateFavoriteStatus(ctx context.Context, in *userOptPb2.UpdateFavoriteStatusReq) (*userOptPb2.UpdateFavoriteStatusResp, error) {
	l := logic2.NewUpdateFavoriteStatusLogic(ctx, s.svcCtx)
	return l.UpdateFavoriteStatus(in)
}
