// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	UserName string `form:"username"`
	Password string `form:"password"`
}

type IdWithTokenReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type Status struct {
	Code int64  `json:"status_code"`
	Msg  string `json:"status_msg,omitempty"`
}

type IdWithTokenRes struct {
	UserId int64  `json:"user_id,omitempty"`
	Token  string `json:"token,omitempty"`
}

type UserRegisterReq struct {
	UserReq
}

type UserRegisterRes struct {
	Status
	IdWithTokenRes
}

type UserLoginReq struct {
	UserReq
}

type UserLoginRes struct {
	Status
	IdWithTokenRes
}

type User struct {
	UserId        int64  `json:"id"`
	UserName      string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type UserInfoReq struct {
	IdWithTokenReq
}

type UserInfoRes struct {
	Status
	User *User `json:"user,omitempty"`
}
