// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChat = "chat"

// Chat mapped from table <chat>
type Chat struct {
	ID         uint      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Msg        string    `gorm:"column:msg;type:text;not null" json:"msg"`
	Sender     uint      `gorm:"column:sender;type:int;not null" json:"sender"`
	Receiver   uint      `gorm:"column:receiver;type:int;not null" json:"receiver"`
	Createtime time.Time `gorm:"column:createtime;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"createtime"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
