// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	ID      uint   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID  uint   `gorm:"column:user_id;type:int" json:"user_id"`
	FunID   uint   `gorm:"column:fun_id;type:int;not null" json:"fun_id"`
	Removed uint   `gorm:"column:removed;type:tinyint;not null" json:"removed"`
	Msg     string `gorm:"column:msg;type:text" json:"msg"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
