// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         uint      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Username   string    `gorm:"column:username;type:varchar(32);not null" json:"username"`
	Password   string    `gorm:"column:password;type:varchar(32);not null" json:"password"`
	Enable     uint      `gorm:"column:enable;type:tinyint;default:1" json:"enable"`
	Type       uint      `gorm:"column:type;type:tinyint;not null" json:"type"`
	LoginTime  time.Time `gorm:"column:login_time;type:datetime;default:CURRENT_TIMESTAMP" json:"login_time"`
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
