// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID       uint   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AuthorID uint   `gorm:"column:author_id;type:int;not null" json:"author_id"`
	PlayURL  string `gorm:"column:play_url;type:varchar(32);not null" json:"play_url"`
	CoverURL string `gorm:"column:cover_url;type:varchar(32);not null" json:"cover_url"`
	Time     uint   `gorm:"column:time;type:int;not null" json:"time"`
	Title    string `gorm:"column:title;type:varchar(128);not null" json:"title"`
	Removed  uint   `gorm:"column:removed;type:tinyint;not null" json:"removed"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
