// Code generated by goctl. DO NOT EDIT!
// Source: minio-client.proto

package uploadfile

import (
	"context"

	"douyin/pkg/minio-client/types/minio-client"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UploadFileReply   = minio_client.UploadFileReply
	UploadFileRequest = minio_client.UploadFileRequest

	UploadFile interface {
		UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error)
	}

	defaultUploadFile struct {
		cli zrpc.Client
	}
)

func NewUploadFile(cli zrpc.Client) UploadFile {
	return &defaultUploadFile{
		cli: cli,
	}
}

func (m *defaultUploadFile) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error) {
	client := minio_client.NewUploadFileClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}
