// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	userOpt "douyin/pkg/favorite/api/internal/handler/userOpt"
	"douyin/pkg/favorite/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/favorite/action",
					Handler: userOpt.FavoriteOptHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/favorite/list",
					Handler: userOpt.GetFavoriteListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)

}
