// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "comment/api/internal/handler/comment"
	"comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/comment/action",
				Handler: comment.CommentActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/comment/list",
				Handler: comment.CommentListHandler(serverCtx),
			},
		},
	)
}
