// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videoservice

import (
	"context"
	video2 "douyin/pkg/video/types/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAllVideoByUserIdReq  = video2.GetAllVideoByUserIdReq
	GetAllVideoByUserIdResp = video2.GetAllVideoByUserIdResp
	GetVideoReq             = video2.GetVideoReq
	GetVideoResp            = video2.GetVideoResp
	PublishVideoReq         = video2.PublishVideoReq
	PublishVideoResp        = video2.PublishVideoResp
	User                    = video2.User
	Video                   = video2.Video

	VideoService interface {
		PublishVideo(ctx context.Context, in *PublishVideoReq, opts ...grpc.CallOption) (*PublishVideoResp, error)
		GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error)
		GetAllVideoByUserId(ctx context.Context, in *GetAllVideoByUserIdReq, opts ...grpc.CallOption) (*GetAllVideoByUserIdResp, error)
	}

	defaultVideoService struct {
		cli zrpc.Client
	}
)

func NewVideoService(cli zrpc.Client) VideoService {
	return &defaultVideoService{
		cli: cli,
	}
}

func (m *defaultVideoService) PublishVideo(ctx context.Context, in *PublishVideoReq, opts ...grpc.CallOption) (*PublishVideoResp, error) {
	client := video2.NewVideoServiceClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetVideo(ctx context.Context, in *GetVideoReq, opts ...grpc.CallOption) (*GetVideoResp, error) {
	client := video2.NewVideoServiceClient(m.cli.Conn())
	return client.GetVideo(ctx, in, opts...)
}

func (m *defaultVideoService) GetAllVideoByUserId(ctx context.Context, in *GetAllVideoByUserIdReq, opts ...grpc.CallOption) (*GetAllVideoByUserIdResp, error) {
	client := video2.NewVideoServiceClient(m.cli.Conn())
	return client.GetAllVideoByUserId(ctx, in, opts...)
}
