// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type UserInfoRes struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	User       User   `json:"user"`
}

type User struct {
	Id            string `json:"userId"`
	Name          string `json:"name"`
	FollowCount   int    `json:"follow_count"`
	FollowerCount int    `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}
