// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	feed "douyin/pkg/gateway/internal/handler/feed"
	message "douyin/pkg/gateway/internal/handler/message"
	publish "douyin/pkg/gateway/internal/handler/publish"
	user "douyin/pkg/gateway/internal/handler/user"
	userOpt "douyin/pkg/gateway/internal/handler/userOpt"
	"douyin/pkg/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/favorite/action",
					Handler: userOpt.FavoriteOptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/comment/action",
					Handler: userOpt.CommentOptHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/relation/action",
					Handler: userOpt.FollowOptHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/favorite/list",
					Handler: userOpt.GetFavoriteListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/comment/list",
					Handler: userOpt.GetCommentListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/follow/list",
					Handler: userOpt.GetFollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/relation/follower/list",
					Handler: userOpt.GetFollowerListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: user.UserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/action",
					Handler: publish.PublishVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: publish.GetPublishVideoListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin/publish"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: feed.FeedVideoListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/feed"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthJWT},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/message/action",
					Handler: message.MessageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/message/chat",
					Handler: message.MessagelistHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/douyin"),
	)
}
