// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"
	logic2 "douyin/pkg/follow/internal/logic"
	"douyin/pkg/follow/internal/svc"
	follow2 "douyin/pkg/follow/types/follow"
)

type FollowServiceServer struct {
	svcCtx *svc.ServiceContext
	follow2.UnimplementedFollowServiceServer
}

func NewFollowServiceServer(svcCtx *svc.ServiceContext) *FollowServiceServer {
	return &FollowServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServiceServer) Follow(ctx context.Context, in *follow2.FollowReq) (*follow2.FollowResp, error) {
	l := logic2.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *FollowServiceServer) GetFollowList(ctx context.Context, in *follow2.GetFollowListReq) (*follow2.GetFollowListResp, error) {
	l := logic2.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}

func (s *FollowServiceServer) GetFollowerList(ctx context.Context, in *follow2.GetFollowerListReq) (*follow2.GetFollowerListResp, error) {
	l := logic2.NewGetFollowerListLogic(ctx, s.svcCtx)
	return l.GetFollowerList(in)
}
