apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: favorite
  name: favorite
  namespace: favorite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favorite
  template:
    metadata:
      labels:
        app: favorite
    spec:
      containers:
        - name: favorite
          image: douyin/favorite:nightly
          imagePullPolicy: Never
          ports:
            - containerPort: 8081