// Code generated by goctl. DO NOT EDIT!
// Source: userinfo.proto

package server

import (
	"context"

	"douyin/pkg/userinfo-demo/rpc/internal/logic"
	"douyin/pkg/userinfo-demo/rpc/internal/svc"
	"douyin/pkg/userinfo-demo/rpc/types/userinfo"
)

type UserinfoServer struct {
	svcCtx *svc.ServiceContext
	userinfo.UnimplementedUserinfoServer
}

func NewUserinfoServer(svcCtx *svc.ServiceContext) *UserinfoServer {
	return &UserinfoServer{
		svcCtx: svcCtx,
	}
}

func (s *UserinfoServer) GetUser(ctx context.Context, in *userinfo.UserinfoRequest) (*userinfo.UserinfoResult, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
