// Code generated by goctl. DO NOT EDIT.
// Source: UserService.proto

package server

import (
	"context"

	"douyin/pkg/user/rpc/internal/logic"
	"douyin/pkg/user/rpc/internal/svc"
	"douyin/pkg/user/rpc/userInfoPb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userInfoPb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------user-----------------------
func (s *UserServiceServer) Register(ctx context.Context, in *userInfoPb.RegisterReq) (*userInfoPb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *userInfoPb.LoginReq) (*userInfoPb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) Info(ctx context.Context, in *userInfoPb.UserInfoReq) (*userInfoPb.UserInfoResp, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
