// Code generated by goctl. DO NOT EDIT.
// Source: UserComment.proto

package server

import (
	"context"
	logic2 "douyin/pkg/comment/internal/logic"
	"douyin/pkg/comment/internal/svc"
	userCommentPb2 "douyin/pkg/comment/userCommentPb"
)

type UserCommentServer struct {
	svcCtx *svc.ServiceContext
	userCommentPb2.UnimplementedUserCommentServer
}

func NewUserCommentServer(svcCtx *svc.ServiceContext) *UserCommentServer {
	return &UserCommentServer{
		svcCtx: svcCtx,
	}
}

// -----------------------userCommentStatus-----------------------
func (s *UserCommentServer) UpdateCommentStatus(ctx context.Context, in *userCommentPb2.UpdateCommentStatusReq) (*userCommentPb2.UpdateCommentStatusResp, error) {
	l := logic2.NewUpdateCommentStatusLogic(ctx, s.svcCtx)
	return l.UpdateCommentStatus(in)
}

// -----------------------userCommentList-----------------------
func (s *UserCommentServer) GetVideoComment(ctx context.Context, in *userCommentPb2.GetVideoCommentReq) (*userCommentPb2.GetVideoCommentReqResp, error) {
	l := logic2.NewGetVideoCommentLogic(ctx, s.svcCtx)
	return l.GetVideoComment(in)
}
