apiVersion: apps/v1
kind: Deployment
metadata:
  name: douyin-api-svc
  namespace: douyin-comment
  labels:
    app: douyin-api-svc
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: douyin-api-svc
  template:
    metadata:
      labels:
        app: douyin-api-svc
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: douyin-api-svc
        image: douyin-comment-api:v1
        ports:
        - containerPor
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: douyin-api-svc-svc
  namespace: douyin-comment
spec:
  ports:
  - nodePort: 32010
    port: 8888
    protocol: TCP
    targetPort: 8888
  type: NodePort
  selector:
    app: douyin-api-svc

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: douyin-api-svc-hpa-c
  namespace: douyin-comment
  labels:
    app: douyin-api-svc-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: douyin-api-svc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: douyin-api-svc-hpa-m
  namespace: douyin-comment
  labels:
    app: douyin-api-svc-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: douyin-api-svc
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
