// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/minio-client.proto

package minio_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UploadFileClient is the client API for UploadFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadFileClient interface {
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error)
}

type uploadFileClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadFileClient(cc grpc.ClientConnInterface) UploadFileClient {
	return &uploadFileClient{cc}
}

func (c *uploadFileClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileReply, error) {
	out := new(UploadFileReply)
	err := c.cc.Invoke(ctx, "/minio_client.UploadFile/UploadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadFileServer is the server API for UploadFile service.
// All implementations must embed UnimplementedUploadFileServer
// for forward compatibility
type UploadFileServer interface {
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error)
	mustEmbedUnimplementedUploadFileServer()
}

// UnimplementedUploadFileServer must be embedded to have forward compatible implementations.
type UnimplementedUploadFileServer struct {
}

func (UnimplementedUploadFileServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedUploadFileServer) mustEmbedUnimplementedUploadFileServer() {}

// UnsafeUploadFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadFileServer will
// result in compilation errors.
type UnsafeUploadFileServer interface {
	mustEmbedUnimplementedUploadFileServer()
}

func RegisterUploadFileServer(s grpc.ServiceRegistrar, srv UploadFileServer) {
	s.RegisterService(&UploadFile_ServiceDesc, srv)
}

func _UploadFile_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadFileServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minio_client.UploadFile/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadFileServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UploadFile_ServiceDesc is the grpc.ServiceDesc for UploadFile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadFile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minio_client.UploadFile",
	HandlerType: (*UploadFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFile",
			Handler:    _UploadFile_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/minio-client.proto",
}
