apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: gateway
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: douyin/gateway:nightly
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
