apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio-client
  name: minio-client
  namespace: minio-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio-client
  template:
    metadata:
      labels:
        app: minio-client
    spec:
      containers:
        - name: minio-client
          image: douyin/minio-client:nightly
          imagePullPolicy: Never
          ports:
            - containerPort: 30001